### ISSUE TITLE
Вылезание текста прямого эфира при переключениях

### ISSUE THREAD

**Issue by Orhideous** [Orhideous/tabun#8]
Ошибка в стилях приводит к перекрытию блоков

**Comment by zluca** [comment]
Косяк в скрипте [main.bundle.js](https://cdn.everypony.ru/static/f0c579a9fe9ab3b3d909/main.bundle.js). После успешного ажакс запроса он подменяет хтмл блока .js-block-stream-content и зачем то прописывает ему высоту в свойства элемента. Лечится удалением из скрипта строки: 

> e.height(e.height()),

Коммит не пишу так тут всё сложна для меня. :D
